### ISSUE TITLE
BPIP-3: Pre-minted Vouchers (Shell rNFTs)

### ISSUE THREAD

**Issue by cliffhall** [bosonprotocol/BPIPs#3]
[The proposal](https://github.com/bosonprotocol/BPIPs/blob/main/content/BPIP-3.md) describes a new feature which allows sellers to pre-mint vouchers, making them available for primary purchase on NFT marketplaces.

**Comment by thecryptofruit** [comment]
Hi @cliffhall, do you mind adding `author` field to the proposal? Thanks!
